Summary order page
bold-commerce/checkout-react-templates pull request #15
Opened 2021-11-19 15:09 UTC by TimeBones

Created order summary page
Added icons
Updated Inventory page with icons

2021-11-19 15:27 UTC, CalinR requested changes

2021-11-19 15:27 UTC, CalinR commented on one_click/client/components/OneClickLayout/components/Icons/CaretRight.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Do we still need these .svg files? I think since you have the .jsx versions you can probably remove these ones.

2021-11-19 16:45 UTC, arvinder-bold commented on one_click/client/components/OneClickLayout/components/Icons/CaretRight.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
+1 to this. We can exclude svg files and since these jsx components will never change, you can memoize them too. `export default React.memo(CaretRight) for ex;

2021-11-19 16:56 UTC, travisblair commented on one_click/client/components/OneClickLayout/components/Summary/SummaryItem.jsx
> +                { removable &&
would it be possible to get rid of the `removable` prop and instead just use `removeItem`?

2021-11-19 16:58 UTC, travisblair commented on one_click/client/components/OneClickLayout/components/Summary/SummaryLine.jsx
> +export default SummaryLine;
this component feels as though it should actually be two separate components

2021-11-19 18:53 UTC, TimeBones commented on one_click/client/components/OneClickLayout/components/Summary/SummaryLine.jsx
> +export default SummaryLine;
As in one component with items and one without? I have it as one component because they mostly start without items but have them added on during the checkout.

2021-11-19 19:00 UTC, travisblair commented on one_click/client/components/OneClickLayout/components/Summary/SummaryLine.jsx
> +export default SummaryLine;
ahh ok that makes a sense.

2021-11-23 15:25 UTC, CalinR approved these changes

2021-11-23 16:22 UTC, closed without merging